version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - RAILS_MASTER_KEY=Vw0m8g4yd3b8WbwnGJh87wgUYIAGIoKo
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
